chapel-lang/pychapel

docs/source/examples/bfiles/chapel/bfile.fib.chpl

Running examples/chapel.bfile.fib.py produced the output 89 as the 10th
fibonacci number, which is not correct.  That is the 11th fibonacci number.
The error arose from using 0 to n as the traversal (n+1 numbers), instead of 1
to n (n numbers).  While I was there, I removed the unnecessary traversal
variable i, since for loops can function without storing their iteration if it
isn't used by the body.

Fix off-by-one error in bfile fibonacci example.

---

docs/source/examples/chapel.sfile.hellolib.ename.py
docs/source/examples/chapel.sfile.hellolib.py

The two examples, chapel.sfile.hellolib.py and chapel.sfile.hellolib.ename.py,
were trying to access a sfile by the name of chapel.hellolib.exported.chpl when
the file was actually named hellolib.exported.chpl.  For consistency with the
other bfile and sfile names, I changed the python files rather than the name of
the file itself.

Use correct file name

---

module/setup.py

There is a chicken/egg problem when importing pych.version in setup.py, which is used to install the pych module. Update setup.py to read the version.py file (not import it) and then grab the version/name.

Do not import pych during install process.

---

docs/source/conf.py
module/setup.py

Read the Docs wasn't able to find the version.py module, so we altered its
usage in docs/source/conf.py.  Change is based on Thomas's similar change to
module/setup.py

Fix broken doc build.

---

util/test_python.bash

Previously, Travis would report that the script passed when the py.test run
failed but the pych --testing run passed because the pych run happened last.
This allows Travis to tell us something went wrong in the first case.

Allow Travis to fail when the result of the py.test run fails

---

docs/source/examples/test_begin.py
docs/source/examples/test_chapel_sfile.py
docs/source/examples/test_cobegin.py
docs/source/examples/test_for.py
docs/source/examples/test_forall.py
docs/source/examples/test_sync.py
docs/source/examples/test_unusual_sfile_loc.py
docs/source/examples/testcase.py

Py.test's capfd and capsys depend on certain circumstances to be true - namely,
that output is placed in a specific place.  With our Jenkins run, that is not
the case - either because of how python is set up to interact with Chapel or how
Chapel is set up, but all unique to Jenkins.  It doesn't really matter (though I am
curious).  It is still useful to have output tests, so instead of trying to depend on
py.test's built in functionality, implement our own method of capture (based in
part on the testing structure we built to ensure chplforpyp-docs examples work)
Because this method captures the initial message about creating a temporary
file for the materialized Chapel code (which only occurs the first time a test
is run), some of the previous assumptions about the output "starting with" …

Fix output dependent tests

---

docs/source/examples/bfiles/chapel/material.file1.chpl
docs/source/examples/bfiles/chapel/material.file2.chpl
docs/source/examples/test_materialization_conflict_A.py
docs/source/examples/test_materialization_conflict_B.py

This circumstance was encountered through py.test but is more
reasonably captured in a single case.  When two modules that
are used in a single program try to access two separate
external functions that share a name, the first function accessed
will be used in both cases.  I think that the materialization of
functions (and use of cached materializations) should take into
account the source location of the external function, so that
if the current source and the previous source differ, both will be
accessed under the correct circumstances.
If we have support for accessing multiple modules in a Chapel file, it'd be nice
for the separate materialization to apply to functions in separate modules.
That will probably be tricky, though.

Add a test which fails

---

docs/source/examples/bfiles/chapel/arbitraryfile.chpl
docs/source/examples/bfiles/chapel/user.chpl
docs/source/examples/sfiles/chapel/arbitraryfile.chpl
docs/source/examples/sfiles/chapel/user.chpl
docs/source/examples/test_arbitrary_chapel_use.py
docs/source/examples/test_bfile_arbitrary_chapel.py
docs/source/examples/test_inline_arbitrary_chapel.py

Unfortunately, right now we cannot include use statements that reference Chapel
code which is not present in the internal or standard modules in our exported
or inlined Chapel functions called from Python.  These tests attempt to do so
by placing the other Chapel file in question in the same sfile/bfile location as
the calling code.
Since Chapel module files such as Time have been used in other tests, I remain
hopeful that we can expand pyChapel to make use of specified locations to look
for further Chapel code - however, it is apparent that work needs to be done to
achieve this (I believe c.library.py demonstrates an in-progress attempt at this
functionality, for instance).

Add three tests of using arbitrary Chapel modules within export Chapel code

---

docs/source/examples/sfiles/chapel/exported.and.array.chpl
docs/source/examples/sfiles/chapel/exported.and.not.chpl
docs/source/examples/test_use_nonexported.py
docs/source/examples/test_use_nonexported_array.py

Namely, that export functions can call other Chapel functions in the same file,
and that such called functions at least can make use of types not known to
pyChapel at this time.

Add some tests to lock in behavior with exported functions.

---

docs/source/examples/bfiles/chapel/arbitraryfile.chpl
docs/source/examples/sfiles/chapel/arbitraryfile.chpl
docs/source/examples/test_arbitrary_chapel_use.py
docs/source/examples/test_bfile_arbitrary_chapel.py
docs/source/examples/test_inline_arbitrary_chapel.py
docs/source/examples/test_use_and_name_conflict.py

These tests started failing in our nightly testing suite due to a long standing
bug that had been brought to the forefront by some clean up Michael did in the
Chapel compiler.  The bug is that the assignment operator for records that are
generic on multiple fields doesn't resolve, and the POD clean up looks for a
user-defined assignment overload (while determining if a type is POD or not)
by trying to resolve a call to it.  If the user hasn't defined an overload,
then the compiler runs into this error.  This problem goes away if the record
is only generic for one field, so I altered the type definition, since the extra field
wasn't necessary anyways.

Resolve pyChapel testing errors

---

docs/source/examples/test_no_depends_fails.py

With the new ability to "use" enums, the error message for failing to find a
module had been updated to indicate that we didn't find a module or an enum,
making this test's expected output fail to match.  Update the expected error
message to reflect this new functionality.

Update expected error message in this test

---

requirements.txt

Our testing system uses python 2.6 still, but the latest version of matplotlib
no longer supports that version of python.
We need to get later python support and update our testing system, but for now,
make sure we work in testing.

Quick patch: Force matplotlib version to be less than 1.5

---

module/pych/configuration.py

We switched to a different test machine because that machine had python 2.7
installed on it, but this meant that the configuration file's relative path
used to find the pych.json file wasn't accurate.
This patch doesn't complete resolve that problem, it just delays it while I
think of a better solution.  Should allow testing to pass again.

Fix config error on ubuntu machine

---

README.md

Read the Docs sent out an email saying they were updating their site hosting
to readthedocs.io instead of readthedocs.org.  Though the old link redirects to
the new location automatically, update the link to point to the right spot in
the first place.

Update .readthedocs.org links to point to readthedocs.io

---

module/ext/src/extern.chpl
module/ext/src/ptrToArray.chpl
module/templates/chapel/prefix.chpl

https://github.com/chapel-lang/chapel/pull/4510 added an optimization to remove
an inner `blk` multiply for cases where the compiler could prove it wasn't
needed. However, it's kind of a lame optimization (see the PR for why) and it
requires marking all functions that modify an array's blk field. Pychapel is
messing around with array internals (which it shouldn't really be doing IMO)
so we need to mark the functions that modify blk.

Mark all functions that modify an array's `blk` with the required pragma

---

util/test_python.bash

A shallow clone is ~10X faster. We don't need the full history, so don't waste
time grabbing it.

Only do a shallow clone of chapel-lang instead of a full one

---

module/ext/src/extern.chpl
module/ext/src/ptrToArray.chpl
module/templates/chapel/convert.pych.1d.chpl
module/templates/chapel/prefix.chpl

The PR for the array memory management improvements is here:
https://github.com/chapel-lang/chapel/pull/4762
The initial symptom was compilation failures from the Chapel compiler.
This PR updates pychapel to no longer use 'new _array' and instead use _getArray. Additionally, when creating a Chapel array that refers to a NumPy array, it uses the alias operator so that the array is not copied. Lastly, adjusted the pych_to_chpl1D method in order to add the returned array to the domain so that the domain will be freed with the array (instead of being freed when that function exits and causing core dumps).
Reviewed by @lydia-duncan - thanks!

Fix pychapel after Chapel array memory management improvements

---

docs/source/introduction.rst
module/configs/pych.json
module/ext/src/ptrToArray.chpl
util/test_python.bash

Includes:
- Remove use of deprecated noRefCount flag from Chapel compilation
- Adjust for new build system
Remove use of deprecated noRefCount flag from Chapel compilation
---------------------------------------------------------------------------------------
This flag was removed in Chapel PR [4912,](https://github.com/chapel-lang/chapel/pull/4912)
as a clean up from it no longer being useful.  It was also no longer needed in
pyChapel, as the fix it was providing had been performed in another manner
after the array rework, so I removed the flag and the comment referencing
why it was used in the first place.
Verified that one of the failing tests now passes.  Travis verified full
testing.
Adjust for new build system
----------------------------------
With the build updates to the Chapel …

Various updates due to Chapel repo improvements

---

module/pych/version.py

Bump version number in prep for release with fixes for Chapel's build system
and the removal of the noRefCount flag.
Should've done this back in December.  Thankfully, we don't seem to need
more updates (that I can tell)

Prep for latest release

---

module/ext/src/extern.chpl
module/ext/src/ptrToArray.chpl
module/templates/chapel/prefix.chpl

This reverts commit 57ab950da22cc1d2eb18fbf1173af83c77393261.
Remove the "modifies array blk" pragma from pychapel. This pragma (and the
optimization it corresponded to) have been obsoleted by array-views. See
https://github.com/chapel-lang/chapel/pull/5548 for more info.

Revert "Mark all functions that modify an array's `blk` with the required pragma

---

docs/source/examples/test_finance_chapel_numpy_flatten.py
docs/source/examples/test_modify_array_argument_reals.py
docs/source/examples/test_modify_local_array_copy_reals.py
docs/source/examples/test_multiple_array_args_reals.py
docs/source/examples/test_return_array_reals.py
docs/source/examples/test_small_array_int.py
docs/source/examples/test_small_array_reals.py
docs/source/examples/test_sparse_array_error_msg.py
module/ext/src/extern.chpl
module/ext/src/ptrToArray.chpl
module/templates/chapel/convert.pych.1d.chpl
module/templates/chapel/prefix.chpl

When [the array views branch](https://github.com/chapel-lang/chapel/pull/5338)
was merged into the Chapel implementation, we started experiencing a failure
with test_finance_chapel_numpy.py.  This commit will quiet the pyChapel nightly
testing.  It also makes some other improvements along the way.
The issue was that the array views implementation removed the need for the
blk field on DefaultRectangular arrays, but the pyChapel support of passing
numpy arrays to Chapel relied on this field being present.  Numpy arrays can
be sparsely packed under certain circumstances, which were exercised by the
test in question: loading a file to create multiple arrays at once.  The arrays
themselves knew that they only referred to one column, but the data was not
separated when creating these arrays, …

Avoid/fix failure for test after array views merge in the Chapel implementation

---

util/test_python.bash

The Travis build started failing because it had an older version of pytest and
our installation of the requirements file didn't force it to get the latest
version of the package.  Force the installation to upgrade any packages it
installs in that step.

Force testing script to grab the latest version of pytest

---

docs/source/introduction.rst
docs/source/usage.rst
docs/source/usage_examples.rst

Some of the :lines: numbers of the .py scripts included in
usage_examples.rst were out of date.  Update them.
Many of the :lines: lines in introduction.rst and usage.rst included
an extra blank line at the end.  Remove them.

Update line numbers

---

docs/source/usage_examples.rst

The documentation indicated that the translation to Chapel was simple, however
in some cases the arrays need to be flattened before they can be sent to a
Chapel program.  Note that possibility before users run into it.
Verified that the documentation output looked okay.

Document that we need to flatten sparsely packed numpy arrays

---

docs/source/examples/test_no_depends_fails.py

PR 6370 on the chapel repository caused a change to the error message output
when a Chapel module or enum can't be found in a use statement, resulting in
the failure of this test to match expected output.  Update accordingly.

Update expected error message for this test

---

module/configs/pych.json
requirements.txt

Fixes pychapel build on Ubuntu 16.04 and SLES 12.2

Remove pip version constraints and -lgmp dependency. Add Python<3.0 requirement.

---

util/test_python.bash

This change fixes the build failure "[SSL: CERTIFICATE_VERIFY_FAILED]"
when pip tries to download setuptools_scm to satisfy a dependency of
pytest-xdist-1.20.0, which happened consitently on various Cray internal
SLES build slaves since Aug 09 (except on chap05, where the error
never happened)
Suggested by: https://github.com/pypa/pypi-legacy/issues/322,
search for: "I did pip install setuptools_scm and it solved the problem"

Add "pip install setuptools_scm" to test script, avoid fatal error

---

docs/source/conf.py
docs/source/index.rst

Remove [usage other](http://pychapel.readthedocs.io/usage_other.html) section from docs until it's more fleshed out and better supported.
Kind of resolves #79

Remove "Usage Other" from docs

---

docs/source/conf.py
docs/source/configuration.rst
docs/source/introduction.rst
docs/source/pych/notes.rst
module/README.txt
module/pych/version.py
module/scripts/pych
module/setup.py
util/test_python.bash

Makes the pip install (w manual Chapel build) work on Linux again, without addressing everything else to be desired. 
This should at least get pychapel back the functionality it had, before 
* Chapel changed its internal runtime lib path
* The last two pypi releases, which were incomplete ("pych.json not found")

pychapel 0.1.18: Fix lib path for Chapel > 1.16.0; pip installer; docs.

---

docs/source/requirements.txt

The previous commit did not work.

Fix pychapel.readthedocs.io's auto-build

---

docs/source/requirements.txt
requirements.txt

Issue #95 : workaround fixes unit test failures by avoiding the
newest matplotlib/2.2.0 version, which now requires python bz2
module, which we do not have on our test system.
pychapel itself does not need bz2.

Constrain matplotlib<2.2.0 in "requirements.txt"
